### ISSUE TITLE
where is the runMaster.sh?

### ISSUE THREAD

**Issue by ZiqiChai** [cmitash/PHYSIM_6DPose#1]
I didn't see the runMaster.sh file under PHYSIM_6DPose_PATH?  Why?

**Comment by cmitash** [comment]
My bad. I added the file now. Thanks for pointing out.

**Comment by ZiqiChai** [comment]
thanks.When i run "make" in matlab, it shows:
Checking subfolder "FastGlobalRegistration" for custom messages.
Warning: The folder /home/aemc/PHYSIM_6DPose/src/FastGlobalRegistration does not contain a valid ROS package, because the

'package.xml' file is missing. Create the 'package.xml' file in this folder.
Checking subfolder "physics-scene-rendering-vision" for custom messages.

Warning: The folder /home/aemc/PHYSIM_6DPose/src/physics-scene-rendering-vision does not contain a valid ROS package, because
the 'package.xml' file is missing. Create the 'package.xml' file in this folder.
Checking subfolder "rgbd-utils" for custom messages.
Warning: The folder /home/aemc/PHYSIM_6DPose/src/rgbd-utils does not contain a valid ROS package, because the 'package.xml'
file is missing. Create the 'package.xml' file in this folder.
Checking subfolder "super4pcs" for custom messages.
Warning: The folder /home/aemc/PHYSIM_6DPose/src/super4pcs does not contain a valid ROS package, because the 'package.xml'

file is missing. Create the 'package.xml' file in this folder.

Then I think the ROS  msgs were not built. So is there anything missing? or I miss any command?
Thanks.




At 2018-03-13 21:58:41, "Chaitanya Mitash" <notifications@github.com> wrote:


My bad. I added the file now. Thanks for pointing out.
